export const REQUEST_NEWS = "REQUEST_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";
export const REQUEST_PREV_NEWS = "REQUEST_PREV_NEWS";

